# -*- mode: ruby -*-
# vi: set ft=ruby :

#VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">= 1.3.5"

require 'yaml'
require 'fileutils'
$script = <<-SCRIPT
echo '****provisioning python3****'
sudo apt-get install python3 -y
echo '****provisioning python2****'
sudo apt-get install python -y
echo '****provisioning python3-pip****'
sudo apt-get install python3-pip -y
echo '****provisioning python-pip***
sudo apt-get install python-pip -y
echo '****provisioning Ansible****'
sudo pip3 install ansible 
echo '****provisioning pywinrm****'
sudo pip3 install pywinrm
echo '****provisioning sshpass***'
sudo pip3 install sshpass
echo '****provisioning python3 boto3****'
sudo pip3 install boto3
echo '****provisioning python3 boto****'
sudo pip3 install boto
echo '****provisioning boto****'
sudo pip install boto
echo '****provisioning python boto3****'
sudo pip install boto3
echo '****done provisoning****'
echo '****create /etc/ansible directory ****'
sudo mkdir /etc/ansible
echo '****get ec2.py script and ec2.ini****'
echo '****be sure to modify ec2.ini to appropriate region!!!****'
sudo wget -P /etc/ansible https://raw.githubusercontent.com/ansible/ansible/devel/contrib/inventory/ec2.ini
sudo wget -P /etc/ansible https://raw.githubusercontent.com/ansible/ansible/devel/contrib/inventory/ec2.py
echo '****modify .bashrc****'
echo "## Modify for Ansible "
echo "alias adir='cd /home/ansible'" >> /home/vagrant/.bashrc
echo "adir" >> /home/vagrant/.bashrc
exit
SCRIPT
Vagrant.configure(2) do |config|
	config.vm.box = "ubuntu/bionic64"
##	config.ssh.port = 4422
	config.vm.boot_timeout = 900
	config.ssh.forward_agent = true
	config.ssh.shell = "bash -c  'BASH_ENV=/etc/profile exec bash'"
	config.vm.network :private_network, ip: "192.168.8.3"
	config.vm.network "public_network", bridge: "Dell Wireless 1504 802.11b/g/n (2.4GHz)"
##	config.vm.network "public_network"
	config.vm.synced_folder ".","/vagrant",type: "virtualbox", fsnotify: true
	config.vm.hostname = "AWS-Ansible"
	config.vm.provider :virtualbox do |vb|
		vb.name = "AWSAnsible"
		vb.memory = 2048
		vb.cpus = 2
	config.vm.synced_folder "./ansible", "/home/ansible", :mount_options => ["dmode=755", "fmode=755"]
	config.vm.provision "shell", inline: $script, run: "once"
	end
end
